import { CornerVariant, PropertyColor, SpaceType } from './game-board.enums';

export const GAME_BOARD_COLORS = {
  shell: '#fffdf7',
  shellBorder: '#d3c5b2',
  boardFrame: '#2856b3',
  boardField: '#dce8ff',
  boardInsetBorder: '#000000',
  boardLine: '#294066',
  boardShadow: 'rgba(19, 34, 68, 0.14)',
  boardCenter: '#999',
  boardCenterGlow: 'rgba(255, 255, 255, 0.22)',
  boardCenterText: '#f5f9ff',
  dicePanelSurface: 'linear-gradient(180deg, #d6f3dc 0%, #bee8cf 100%)',
  dicePanelBorder: '#b9e3c3',
  dicePanelInset: 'rgba(255, 255, 255, 0.55)',
  dicePanelText: '#1b2d22',
  diceDieFace: '#fff8f2',
  diceDieEdge: '#eadfd6',
  dicePip: '#1e1b1b',
  diceShadow: 'rgba(34, 55, 42, 0.18)',
  diceGlow: 'rgba(255, 255, 255, 0.45)',
  diceStatus: '#57d88b',
  diceStatusText: '#11311d',
  deedShell: '#f8efe4',
  deedShellBorder: '#d6c0aa',
  deedRail: '#1f58c8',
  deedRailDark: '#173f96',
  deedBody: '#fbf4ea',
  deedBodyInset: '#fffaf3',
  deedRule: '#e1cdb8',
  deedBuy: '#15a43e',
  deedBuyDark: '#0d7f2f',
  deedAuction: '#ffffff',
  deedAuctionText: '#2143a7',
  actionPrimary: '#ffba18',
  actionPrimaryDark: '#f09b00',
  actionPrimaryBorder: '#ffef98',
  actionSecondary: '#f7f2ec',
  actionSecondaryBorder: '#d8c9bb',
  actionSecondaryText: '#2a2a2a',
  playerPanel: '#228558',
  playerPanelBorder: '#185d3f',
  playerPanelText: '#f4fff7',
  playerPanelMuted: 'rgba(244, 255, 247, 0.8)',
  tileSurface: '#fffdf7',
  tileBorder: '#24385d',
  tileText: '#182440',
  tileMuted: '#66718d',
  priceText: '#31415f',
  specialSurface: '#fff0ca',
  specialBorder: '#ddbf71',
  utilitySurface: '#f5f4ef',
  railroadSurface: '#edf1f8',
  taxSurface: '#fde5e0',
  symbolRailroad: '#1b2b4d',
  symbolUtility: '#1d5b99',
  symbolTax: '#b84e40',
} as const;

export const PROPERTY_COLOR_MAP: Record<PropertyColor, string> = {
  [PropertyColor.BROWN]: '#6B4A2E',
  [PropertyColor.CYAN]: '#8FC9DC',
  [PropertyColor.PINK]: '#C24C8B',
  [PropertyColor.ORANGE]: '#D9802C',
  [PropertyColor.RED]: '#C53A33',
  [PropertyColor.YELLOW]: '#DDAE1A',
  [PropertyColor.GREEN]: '#2E7D4F',
  [PropertyColor.BLUE]: '#2B57C6',
};

export const CORNER_COLOR_MAP: Record<CornerVariant, string> = {
  [CornerVariant.GO]: '#2B57C6',
  [CornerVariant.JAIL]: '#D9802C',
  [CornerVariant.PARKING]: '#2E7D4F',
  [CornerVariant.GOTO_JAIL]: '#C53A33',
};

export const SPACE_SYMBOL_MAP: Partial<Record<SpaceType, string>> = {
  [SpaceType.CHANCE]: '🎲',
  [SpaceType.CHEST]: '🎁',
  [SpaceType.RAILROAD]: '🚂',
  [SpaceType.UTILITY]: '💡',
  [SpaceType.TAX]: '💸',
};

export const SPACE_SURFACE_MAP: Partial<Record<SpaceType, string>> = {
  [SpaceType.CHANCE]: GAME_BOARD_COLORS.specialSurface,
  [SpaceType.CHEST]: GAME_BOARD_COLORS.specialSurface,
  [SpaceType.RAILROAD]: GAME_BOARD_COLORS.railroadSurface,
  [SpaceType.UTILITY]: GAME_BOARD_COLORS.utilitySurface,
  [SpaceType.TAX]: GAME_BOARD_COLORS.taxSurface,
};
