import { CornerVariant, PropertyColor, SpaceType } from './game-board.enums';

export const GAME_BOARD_COLORS = {
  shell: '#0e0c14',
  boardFrame: '#0e0c14',
  boardField: '#dce8ff',
  boardCenter: '#1b1727',
  boardCenterSurface: '#f2e7d6',
  boardCenterInset: '#eadbc7',
  boardCenterBorder: '#bca48c',
  boardCenterText: '#f5f9ff',
  widgetSurface: '#fbf4ea',
  widgetSurfaceAlt: '#f4eadb',
  widgetBorder: '#c9b39b',
  widgetHeader: '#245bd1',
  widgetHeaderText: '#f7fbff',
  widgetText: '#182440',
  widgetMuted: '#6a748f',
  widgetAccent: '#ffba18',
  widgetAccentBorder: '#d89100',
  widgetAccentText: '#2b1c00',
  widgetSuccess: '#15a43e',
  widgetSuccessText: '#f8fff9',
  widgetNeutral: '#ffffff',
  widgetNeutralText: '#2143a7',
  dicePanelSurface: '#fbf4ea',
  dicePanelBorder: '#c9b39b',
  dicePanelText: '#182440',
  diceDieFace: '#fff8f2',
  diceDieEdge: '#eadfd6',
  dicePip: '#1e1b1b',
  diceStatus: '#57d88b',
  diceStatusText: '#11311d',
  deedShell: '#fbf4ea',
  deedShellBorder: '#c9b39b',
  deedRail: '#245bd1',
  deedBody: '#fbf4ea',
  deedRule: '#dcc7b1',
  actionPrimary: '#ffba18',
  actionPrimaryBorder: '#d89100',
  actionSecondary: '#f6ede0',
  actionSecondaryBorder: '#d5c2ae',
  actionSecondaryText: '#5b4a3a',
  playerPanel: '#228558',
  playerPanelText: '#f4fff7',
  playerPanelMuted: 'rgba(244, 255, 247, 0.8)',
  tileSurface: '#fffdf7',
  tileBorder: '#24385d',
  tileText: '#182440',
  tileMuted: '#66718d',
  priceText: '#31415f',
  specialSurface: '#fff0ca',
  specialBorder: '#ddbf71',
  utilitySurface: '#f5f4ef',
  railroadSurface: '#edf1f8',
  taxSurface: '#fde5e0',
  symbolRailroad: '#1b2b4d',
  symbolUtility: '#1d5b99',
  symbolTax: '#b84e40',
} as const;

export const PROPERTY_COLOR_MAP: Record<PropertyColor, string> = {
  [PropertyColor.BROWN]: '#6B4A2E',
  [PropertyColor.CYAN]: '#8FC9DC',
  [PropertyColor.PINK]: '#C24C8B',
  [PropertyColor.ORANGE]: '#D9802C',
  [PropertyColor.RED]: '#C53A33',
  [PropertyColor.YELLOW]: '#DDAE1A',
  [PropertyColor.GREEN]: '#2E7D4F',
  [PropertyColor.BLUE]: '#2B57C6',
};

export const CORNER_COLOR_MAP: Record<CornerVariant, string> = {
  [CornerVariant.GO]: '#2B57C6',
  [CornerVariant.JAIL]: '#D9802C',
  [CornerVariant.PARKING]: '#2E7D4F',
  [CornerVariant.GOTO_JAIL]: '#C53A33',
};

export const SPACE_SYMBOL_MAP: Partial<Record<SpaceType, string>> = {
  [SpaceType.CHANCE]: '🎲',
  [SpaceType.CHEST]: '🎁',
  [SpaceType.RAILROAD]: '🚂',
  [SpaceType.UTILITY]: '💡',
  [SpaceType.TAX]: '💸',
};

export const SPACE_SURFACE_MAP: Partial<Record<SpaceType, string>> = {
  [SpaceType.CHANCE]: GAME_BOARD_COLORS.specialSurface,
  [SpaceType.CHEST]: GAME_BOARD_COLORS.specialSurface,
  [SpaceType.RAILROAD]: GAME_BOARD_COLORS.railroadSurface,
  [SpaceType.UTILITY]: GAME_BOARD_COLORS.utilitySurface,
  [SpaceType.TAX]: GAME_BOARD_COLORS.taxSurface,
};
